# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmnt < Formula
  desc "TUI ncdu-style pour naviguer et restaurer des backups restic S3"
  homepage "https://github.com/Frulko/rmnt"
  version "0.1.5"
  license "MIT"

  depends_on "restic"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.5/rmnt_0.1.5_darwin_amd64.tar.gz"
      sha256 "115ad0cf26531dc1ebadb26e3e7a1dc21477d2fbfe7028b0fe00528616c33391"

      define_method(:install) do
        bin.install "rmnt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.5/rmnt_0.1.5_darwin_arm64.tar.gz"
      sha256 "c39eaffbc6a133e4d9264363d1efda08e572b585929784516b2e2340a449b935"

      define_method(:install) do
        bin.install "rmnt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.5/rmnt_0.1.5_linux_amd64.tar.gz"
      sha256 "db22759c53ed2a9ad625b354172d8a96d20a413349474011868101f7ec4d5896"
      define_method(:install) do
        bin.install "rmnt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.5/rmnt_0.1.5_linux_arm64.tar.gz"
      sha256 "3c9e90968ff523e6498335af5cce937a59ddf296039c139882718244bd2812e5"
      define_method(:install) do
        bin.install "rmnt"
      end
    end
  end

  test do
    system "#{bin}/rmnt", "--version"
  end
end
