# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmnt < Formula
  desc "TUI ncdu-style pour naviguer et restaurer des backups restic S3"
  homepage "https://github.com/Frulko/rmnt"
  version "0.1.3"
  license "MIT"

  depends_on "restic"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.3/rmnt_0.1.3_darwin_amd64.tar.gz"
      sha256 "5371105ebbd5b8bfbb7024d90cdeb1b674be5eef81286c0c795c4de7f95c551f"

      define_method(:install) do
        bin.install "rmnt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.3/rmnt_0.1.3_darwin_arm64.tar.gz"
      sha256 "eb681e7859ba41841d148476405be502fa351bbbb4550eecfd59bdedea40dbad"

      define_method(:install) do
        bin.install "rmnt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.3/rmnt_0.1.3_linux_amd64.tar.gz"
      sha256 "af1822f33f5f94d204ddda88f706a3a7c6958dda41c1b59b8259c4021f97be28"
      define_method(:install) do
        bin.install "rmnt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Frulko/rmnt/releases/download/v0.1.3/rmnt_0.1.3_linux_arm64.tar.gz"
      sha256 "2e57e539c226170e7d5a6bce43540bac01eb00c46ebaa78763e1c3b51acd4430"
      define_method(:install) do
        bin.install "rmnt"
      end
    end
  end

  test do
    system "#{bin}/rmnt", "--version"
  end
end
